In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
# !nvidia-smi

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
type(scalar.item())

int

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
A = torch.tensor([[
                [0, 1 , 2, 3],
                [10, 18, 23, 5],
                [6, 7, 0, 0]
              ],
              [
                  [0 , 0 , 0 , 0],
                  [6 , 6 , 6 , 6],
                  [3, 3, 3, 3]
              ]
              ])

In [ ]:
A.ndim

3

In [ ]:
A.shape

torch.Size([2, 3, 4])

# random tensors

In [ ]:
random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.9084, 0.6951, 0.4752, 0.0337],
        [0.2871, 0.8403, 0.5596, 0.7851],
        [0.2216, 0.3802, 0.8777, 0.6535]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zeros = torch.zeros((3,1))
zeros

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
ones = torch.ones(size=(2,3,6))
ones

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [ ]:
ones.ndim

3

In [ ]:
ones.dtype

torch.float32

In [ ]:
one2ten = torch.arange(start=1,end=110, step=21)

In [ ]:
one2ten

tensor([  1,  22,  43,  64,  85, 106])

In [ ]:
ten_zeros = torch.zeros_like(one2ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

In [ ]:
f32_tensor = torch.tensor([3.0, 6.0, 9.0],
                          dtype=torch.float,
                          device='cpu',
                          requires_grad=False)
f32_tensor

tensor([3., 6., 9.])

In [ ]:
f32_tensor.dtype

torch.float32

In [ ]:
f16_tensor = f32_tensor.type(torch.half)

In [ ]:
f16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(f16_tensor * f32_tensor).dtype

torch.float32

In [ ]:
i32_tensor = torch.tensor([3, 4, 9], dtype=torch.int32)
i32_tensor

tensor([3, 4, 9], dtype=torch.int32)

In [ ]:
i32_tensor * f16_tensor

tensor([ 9., 24., 81.], dtype=torch.float16)

In [ ]:
# tensor info
some_tensor = torch.rand(size=(3,4),
                         dtype=torch.half,
                         device='cpu')
some_tensor

tensor([[0.1572, 0.8335, 0.1094, 0.7261],
        [0.5425, 0.9102, 0.1323, 0.3608],
        [0.3818, 0.8604, 0.1709, 0.3994]], dtype=torch.float16)

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} or {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1572, 0.8335, 0.1094, 0.7261],
        [0.5425, 0.9102, 0.1323, 0.3608],
        [0.3818, 0.8604, 0.1709, 0.3994]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4]) or torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
t = torch.tensor([1, 2, 3])
t+10

tensor([11, 12, 13])

In [ ]:
t * 10

tensor([10, 20, 30])

In [ ]:
t - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(t, 20)

tensor([20, 40, 60])

In [ ]:
torch.add(t, 5)

tensor([6, 7, 8])

In [ ]:
t / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# element-wise multiplication
t * t

tensor([1, 4, 9])

In [ ]:
# dot-product
torch.matmul(t, t)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(t)):
  value += t[i]*t[i]
value

CPU times: user 1.4 ms, sys: 0 ns, total: 1.4 ms
Wall time: 1.41 ms


tensor(14)

In [ ]:
%%time
torch.matmul(t,t)

CPU times: user 1.07 ms, sys: 0 ns, total: 1.07 ms
Wall time: 996 µs


tensor(14)

In [ ]:
%%time
t @ t

CPU times: user 1.08 ms, sys: 6 µs, total: 1.09 ms
Wall time: 1.11 ms


tensor(14)

In [ ]:
torch.matmul(torch.rand(3,5), torch.rand(5, 6))

tensor([[1.4976, 1.2451, 0.4552, 1.6894, 0.8505, 1.0661],
        [1.5145, 1.3651, 0.5701, 1.6538, 1.2255, 1.1418],
        [1.5898, 1.6229, 0.5564, 2.2086, 1.2359, 1.5257]])

In [ ]:
# shape errors
tA = torch.tensor([[1, 2],
                   [3, 4],
                   [5, 6]])
tB = torch.tensor([[7, 10],
                   [8, 11],
                   [9,12]])
# matmul, @
torch.mm(tA, tB)

RuntimeError: ignored

In [ ]:
tA.shape, tB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# transponse
tB.T, tB.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tB, tB.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
print(f"Original shapes: tA: {tA.shape}, and tB: {tB.shape}")
print(f"New shapes: tA: {tA.shape}, and tB.T: {tB.T.shape}")
torch.mm(tA, tB.T) # [3,2] x [2, 3]

Original shapes: tA: torch.Size([3, 2]), and tB: torch.Size([3, 2])
New shapes: tA: torch.Size([3, 2]), and tB.T: torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
## Tensor aggregation

In [ ]:
x = torch.arange(start=1, end=100, step=10)
x.min(), x.max()

(tensor(1), tensor(91))

In [ ]:
torch.mean(x, dtype=torch.float)

tensor(46.)

In [ ]:
x.dtype

torch.int64

In [ ]:
x.type(torch.float).mean()

tensor(46.)

In [ ]:
torch.sum(x)

tensor(460)

In [ ]:
x.sum()

tensor(460)

In [ ]:
# find min and manx
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
y = torch.rand((30,))
y = y*10

In [ ]:
y

tensor([5.3864, 1.1892, 5.7891, 5.0118, 3.1110, 1.6229, 5.9734, 6.4998, 7.9330,
        5.3848, 8.0414, 2.0500, 9.3918, 3.2076, 4.4640, 6.5438, 4.7931, 4.2796,
        0.9946, 4.4020, 4.2139, 5.9827, 6.5187, 2.3660, 5.6487, 9.2813, 4.2385,
        3.9978, 9.5443, 7.4059])

In [ ]:
print(f"min idx: {y.argmin()} with value: {y[y.argmin()]}")
print(f"max idx: {y.argmax()} with value: {y[y.argmax()]}")

min idx: 18 with value: 0.9946072101593018
max idx: 28 with value: 9.544255256652832


In [ ]:
# reshape, must be compatible to the original size
x = torch.arange(1., 10.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
# change of view
z = x.view(1, 10) # z/x share the same area of memory
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
z[:, 1] = 4
z, x

(tensor([[ 1.,  4.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 1.,  4.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# stacking
x_stacked = torch. stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[ 1.,  1.,  1.,  1.],
         [ 4.,  4.,  4.,  4.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]),
 torch.Size([10, 4]))

In [ ]:
image = torch.zeros(1, 256, 1, 23, 45)
image.shape

torch.Size([1, 256, 1, 23, 45])

In [ ]:
k = image.squeeze()
k.shape

torch.Size([256, 23, 45])

In [ ]:
k.unsqueeze(2).shape

torch.Size([256, 23, 1, 45])

In [ ]:
x

tensor([ 1.,  4.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x_reshaped.squeeze()

tensor([ 1.,  4.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# torch.permute
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(dims=(2,0,1))
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_original[0, 0, 1] = 1000
x_original[0, 0, 1], x_permuted[0, 0, 1]

(tensor(1000.), tensor(0.7949))

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][2]

tensor(6)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[0, 1, 1:3]

tensor([5, 6])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0, :, 2]

tensor([3, 6, 9])

In [ ]:
array = np.arange(1., 8.)
t = torch.from_numpy(array)
array, t

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
t.dtype

torch.float64

In [ ]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
array += 1

In [ ]:
array, t

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
t2 = torch.ones(7)
np_t2 = t2.numpy()
t2, np_t2

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
t2 += 2

In [ ]:
t2, np_t2

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([3., 3., 3., 3., 3., 3., 3.], dtype=float32))

In [ ]:
t1 = torch.rand(3,4)
t2 = torch.rand(3,4)
print(t1)
print(t2)
print(t1 == t2)

tensor([[0.6718, 0.0170, 0.9324, 0.7959],
        [0.0785, 0.9895, 0.2514, 0.7802],
        [0.9870, 0.0660, 0.7690, 0.5401]])
tensor([[0.4834, 0.5975, 0.5762, 0.6676],
        [0.1912, 0.7047, 0.8587, 0.8935],
        [0.3174, 0.4751, 0.2226, 0.0428]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 3456
torch.manual_seed(RANDOM_SEED)
t3 = torch.rand(3,4)
t4 = torch.rand(3,4)
print(t3)
print(t4)

torch.manual_seed(RANDOM_SEED)
t5 = torch.rand(3,4)
print(t5)
print(t3==t5)


tensor([[0.6517, 0.3496, 0.5198, 0.6667],
        [0.0500, 0.0059, 0.9915, 0.3813],
        [0.2379, 0.7287, 0.1711, 0.0910]])
tensor([[0.0293, 0.4951, 0.0342, 0.5341],
        [0.4176, 0.1616, 0.8929, 0.9942],
        [0.1410, 0.9678, 0.1950, 0.5737]])
tensor([[0.6517, 0.3496, 0.5198, 0.6667],
        [0.0500, 0.0059, 0.9915, 0.3813],
        [0.2379, 0.7287, 0.1711, 0.0910]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Wed Jul 26 14:01:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [5]:
t = torch.tensor([1, 2, 3])
print(t, t.device)

tensor([1, 2, 3]) cpu


In [6]:
# sposto il tensore t sulla GPU se presente
t2 = t.to(device)
t2

tensor([1, 2, 3], device='cuda:0')

In [10]:
# sposto il tensore t2 dalla gpu alla cpu
t3 = t2.cpu().numpy()

In [11]:
t3

array([1, 2, 3])

In [12]:
t

tensor([1, 2, 3])

In [13]:
t2

tensor([1, 2, 3], device='cuda:0')