In [2]:
import numpy as np
import torch

In [9]:
# Create a random tensor with shape (7, 7).

t_rand = torch.rand(7,7)
t_rand

tensor([[0.3460, 0.3694, 0.1441, 0.4279, 0.6313, 0.9735, 0.9090],
        [0.0036, 0.3853, 0.7027, 0.8339, 0.3110, 0.2265, 0.0612],
        [0.4575, 0.4461, 0.0960, 0.0511, 0.6509, 0.8406, 0.0708],
        [0.1293, 0.5753, 0.5221, 0.2855, 0.5433, 0.6372, 0.9357],
        [0.3431, 0.7238, 0.6227, 0.6073, 0.5297, 0.6119, 0.2376],
        [0.5309, 0.9532, 0.4114, 0.0119, 0.3499, 0.9668, 0.7046],
        [0.5859, 0.1089, 0.0526, 0.8606, 0.5096, 0.7898, 0.9185]])

In [16]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
t2_rand = torch.rand(1,7)
print(t_rand.shape, t2_rand.T.shape)

t3_mul = torch.matmul(t_rand, t2_rand.T)
t3_mul

torch.Size([7, 7]) torch.Size([7, 1])


tensor([[0.9177],
        [0.6631],
        [0.9208],
        [0.9729],
        [1.1808],
        [1.3501],
        [0.7971]])

In [15]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
SEED = 345
torch.manual_seed(SEED)
t1 = torch.rand((7,7))
t2 = torch.rand((1,7))
t3 = torch.matmul(t1, t2.T)
t3

tensor([[1.4484],
        [2.3179],
        [1.9993],
        [1.9164],
        [2.1907],
        [2.1536],
        [1.8881]])

In [16]:
# GPU random seed to 1234
SEED = 1234
torch.cuda.manual_seed(SEED)

a1 = torch.rand((2,3)).to("cuda")
a2 = torch.rand((2,3)).T.to("cuda")
print(a1,a2)

tensor([[0.7514, 0.3789, 0.8548],
        [0.1955, 0.3298, 0.6017]], device='cuda:0')


In [14]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
a3 = torch.matmul(a1, a2)
print(a3)

tensor([[1.0034, 0.6815],
        [1.2955, 1.1320]], device='cuda:0')


In [20]:
# GPU random seed to 1234
SEED = 1234
torch.cuda.manual_seed(SEED)

aa1 = torch.rand((2,3), device="cuda")
aa2 = torch.rand((3,2), device="cuda")
print(aa1, aa2)
aa3 = torch.matmul(aa1, aa2)
print(aa3)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276],
        [0.3255, 0.1114],
        [0.6812, 0.3608]], device='cuda:0')
tensor([[0.7154, 0.2908],
        [1.1616, 0.3998]], device='cuda:0')


In [23]:
# Find the maximum and minimum values of the output of 7.
print(f"min: {aa3.min().item()}, max:{aa3.max().item()}")

min: 0.2907983064651489, max:1.1615904569625854


In [28]:
# Find the maximum and minimum index values of the output of 7.
print(aa3)
print(f"id_max: {aa3.argmax().item()} id_min: {aa3.argmin().item()}")

tensor([[0.7154, 0.2908],
        [1.1616, 0.3998]], device='cuda:0')
id_max: 2 id_min: 1


In [38]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the
# 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create
# it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
B = torch.rand(size=(1, 1, 1, 10))
C = B.squeeze()
print(B.shape, C.shape)

torch.Size([1, 1, 1, 10]) torch.Size([10])


In [39]:
B

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [40]:
C

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])